### ISSUE TITLE
can you provide the pretrained model of LCDNet and LoGG3D-Net

### ISSUE THREAD

**Issue by zouxianghong** [csiro-robotics/SpectralGV#1]
The URLs of pretrained model of LCDNet / LoGG3D-Net are invalid. I'd appreciate it if you could provide me with the trained model.

**Comment by kavisha725** [comment]
Thanks for pointing this out. The link has been made public again. Can you try again and let me know.

**Comment by zouxianghong** [comment]
谢谢，收到

**Comment by zouxianghong** [comment]
thank you so much, the URLs are valid!
